<a href="https://colab.research.google.com/github/ussalbt/Assignment/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
#samples = np.random.normal( mean,std.dev,samplesize)örnekler olacak 
samples = np.random.normal(100,15,1000)
samples

array([ 85.44325872, 122.64763131, 104.743503  ,  91.32730597,
        77.81700001, 107.50207008,  93.31869875,  78.64856302,
        96.10315231,  98.91089936,  90.40661405, 106.25767955,
       107.35691786, 102.2165715 , 113.78559192,  95.12126051,
        97.59979574,  86.30755043, 100.92785416,  82.98742762,
       117.57792826,  65.36530434, 119.0936862 , 102.85298072,
        92.27315712,  99.98520269,  87.60452923,  70.17567981,
        89.07263466, 124.29567467,  88.13587915, 109.94575506,
        92.01264515,  83.38324319, 104.60892723, 106.88254581,
        97.89034966,  92.53115879, 109.43405558, 108.90495249,
        87.69635016, 116.36368461,  96.45338915, 100.42874134,
       130.78692313, 100.84883076, 116.11096428, 100.34031121,
        73.15640415, 110.16767643, 112.86009666, 106.54600052,
        79.81060711, 104.30776766,  80.47887508,  88.84810588,
        92.14796123, 108.02651181,  86.11433747,  86.96059352,
       121.1084095 ,  97.92150451, 115.98092345,  97.78

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)
print("mean:", mean)
print("median:",median)
print("mode:",mode)

mean: 99.92146875909822
median: 100.11708957325502
mode: ModeResult(mode=array([54.01465472]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = np.min(samples)
max =np.max(samples)
q1 = np.percentile(samples,25)
q3 = np.percentile(samples,75)
iqr = q3 - q1
iqr_1 = stats.iqr(samples)
print("max:",max)
print("min:",min)
print("Q1:",q1)
print("Q3:",q3)
print("iqr:",iqr)
print("iqr_1:",iqr_1)

max: 144.25019078349652
min: 54.014654720215916
Q1: 89.52484403971513
Q3: 110.10813628091908
iqr: 20.58329224120395
iqr_1: 20.58329224120395


Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
std_dev = np.std(samples)
print("var:",variance)
print("std:",std_dev)

var: 220.30049258590756
std: 14.842523120612194


Compute the **skewness** and **kurtosis**

In [ ]:
skewness = stats.skew(samples)
print("skewness:",skewness)
kurtosis =stats.kurtosis(samples)
print("kurtosis:",kurtosis)

skewness: -0.0029901545429166974
kurtosis: -0.10346368847290321


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.random.randint(1,1000,10)
print(y)

[152 470 911 610  36 377 476 430 316 359]


Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = np.corrcoef(x,y)
r

array([[ 1.        , -0.12854875],
       [-0.12854875,  1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
print(x)
print(y)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64


Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r =x.corr(y)
r= y.corr(x)
r


0.7586402890911869

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = x.corr(y, method =  "spearman")
rho

0.9757575757575757

In [ ]:
rho = x.corr(y, method = "kendall")
rho

0.911111111111111

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
tips.corr("pearson")

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000